spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common


---

spring:
  config:
    activate:
      on-profile: common


---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: prod